[package]
name = "edit_open"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
tokio = { version = "1.48.0", features = ["net", "time", "macros", "rt", "sync", "io-util", "io-std", "signal"] }
